# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8727ecf4d3f6b85d65298a957df55629ca6de20d623e7695fd70e2e1c9459307e06030975d943c4de15b522adc56c98c27e683358228698b46abb3c0f07c6985

test:
  secret_key_base: dab18a6cd5f90b51e2f9b93df717fc1e0dd16adb450da0d4b87ca7f22ef43f39b93476f75fdbddd8401738386b406298898a7d2d5eee28b45088621fec0b1c24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
